service: lambda-node-oracle

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: sa-east-1
    environment:
      HOSTALIASES: /tmp/HOSTALIASES

functions:
  data-return:
    handler: data-return.handle
    description: método que realiza um pool de conexão e executa uma consulta no banco.
    events:
      - http:
          path: returndata
          method: post
          cors: true

plugins:
  - serverless-offline